<script src="{!! url('public')!!}/assets/plugins/jquery/jquery-1.11.1.min.js"></script>
<script src="{!! url('public')!!}/assets/plugins/jquery/jquery-migrate-1.2.1.min.js"></script>
<script src="{!! url('public')!!}/assets/plugins/jquery-ui/jquery-ui-1.11.2.min.js"></script>
<script src="{!! url('public')!!}/assets/plugins/gsap/main-gsap.min.js"></script>
<script src="{!! url('public')!!}/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="{!! url('public')!!}/assets/plugins/jquery-cookies/jquery.cookies.min.js"></script> <!-- Jquery Cookies, for theme -->
<script src="{!! url('public')!!}/assets/plugins/jquery-block-ui/jquery.blockUI.min.js"></script> <!-- simulate synchronous behavior when using AJAX -->
<script src="{!! url('public')!!}/assets/plugins/translate/jqueryTranslator.min.js"></script> <!-- Translate Plugin with JSON data -->
<script src="{!! url('public')!!}/assets/plugins/bootbox/bootbox.min.js"></script> <!-- Modal with Validation -->
<script src="{!! url('public')!!}/assets/plugins/mcustom-scrollbar/jquery.mCustomScrollbar.concat.min.js"></script> <!-- Custom Scrollbar sidebar -->
<script src="{!! url('public')!!}/assets/plugins/bootstrap-dropdown/bootstrap-hover-dropdown.min.js"></script> <!-- Show Dropdown on Mouseover -->
<script src="{!! url('public')!!}/assets/plugins/charts-sparkline/sparkline.min.js"></script> <!-- Charts Sparkline -->
<script src="{!! url('public')!!}/assets/plugins/retina/retina.min.js"></script> <!-- Retina Display -->
<script src="{!! url('public')!!}/assets/plugins/select2/select2.min.js"></script> <!-- Select Inputs -->
<script src="{!! url('public')!!}/assets/plugins/icheck/icheck.min.js"></script> <!-- Checkbox & Radio Inputs -->
<script src="{!! url('public')!!}/assets/plugins/backstretch/backstretch.min.js"></script> <!-- Background Image -->
<script src="{!! url('public')!!}/assets/plugins/bootstrap-progressbar/bootstrap-progressbar.min.js"></script> <!-- Animated Progress Bar -->
<script src="{!! url('public')!!}/assets/js/sidebar_hover.js"></script> <!-- Sidebar on Hover -->
<script src="{!! url('public')!!}/assets/js/application.js"></script> <!-- Main Application Script -->
<script src="{!! url('public')!!}/assets/js/plugins.js"></script> <!-- Main Plugin Initialization Script -->
<script src="{!! url('public')!!}/assets/js/widgets/notes.js"></script> <!-- Notes Widget -->
<script src="{!! url('public')!!}/assets/js/quickview.js"></script> <!-- Chat Script -->
<script src="{!! url('public')!!}/assets/js/pages/search.js"></script> <!-- Search Script -->
<!-- BEGIN PAGE SCRIPT -->
<script src="{!! url('public')!!}/assets/plugins/noty/jquery.noty.packaged.min.js"></script>  <!-- Notifications -->
<script src="{!! url('public')!!}/assets/plugins/bootstrap-editable/js/bootstrap-editable.min.js"></script> <!-- Inline Edition X-editable -->
<script src="{!! url('public')!!}/assets/plugins/bootstrap-context-menu/bootstrap-contextmenu.min.js"></script> <!-- Context Menu -->
<script src="{!! url('public')!!}/assets/plugins/multidatepicker/multidatespicker.min.js"></script> <!-- Multi dates Picker -->
<script src="{!! url('public')!!}/assets/js/widgets/todo_list.js"></script>
<script src="{!! url('public')!!}/assets/plugins/metrojs/metrojs.min.js"></script> <!-- Flipping Panel -->
<script src="{!! url('public')!!}/assets/plugins/charts-chartjs/Chart.min.js"></script>  <!-- ChartJS Chart -->
<script src="{!! url('public')!!}/assets/plugins/charts-highstock/js/highstock.min.js"></script> <!-- financial Charts -->
<script src="{!! url('public')!!}/assets/plugins/charts-highstock/js/modules/exporting.min.js"></script> <!-- Financial Charts Export Tool -->
<script src="{!! url('public')!!}/assets/plugins/maps-amcharts/ammap/maps/js/worldLow.min.js"></script> <!-- Vector World Map  -->
<script src="{!! url('public')!!}/assets/plugins/maps-amcharts/ammap/themes/black.min.js"></script> <!-- Vector Map Black Theme -->
<script src="{!! url('public')!!}/assets/plugins/skycons/skycons.min.js"></script> <!-- Animated Weather Icons -->
<script src="{!! url('public')!!}/assets/plugins/simple-weather/jquery.simpleWeather.js"></script> <!-- Weather Plugin -->
<script src="{!! url('public')!!}/assets/js/widgets/widget_weather.js"></script>
<script src="{!! url('public')!!}/assets/js/pages/dashboard.js"></script>
<!-- END PAGE SCRIPT -->